package biblioteca.vista;

import biblioteca.entidades.Libro;
import biblioteca.entidades.Prestamo;
import biblioteca.entidades.Usuario;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class Prestamos extends javax.swing.JFrame {

    List<Usuario> usuarios;
    List<Libro> libros;
    List<Prestamo> prestamos;
    Prestamo prestamo;
    Libro libro;
    Usuario usuario;

    public Prestamos() {
        usuarios = new ArrayList<>();
        libros = new ArrayList<>();
        prestamos = new ArrayList<>();
        prestamo = new Prestamo();
        libro = new Libro();
        usuario = new Usuario();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelUsuario = new javax.swing.JPanel();
        txtUserNombre = new javax.swing.JTextField();
        txtUserDni = new javax.swing.JTextField();
        btnUserAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JTextArea();
        panelLibro = new javax.swing.JPanel();
        txtLibroTitulo = new javax.swing.JTextField();
        txtLibroAutor = new javax.swing.JTextField();
        txtLibroPaginas = new javax.swing.JTextField();
        txtLibroUnidades = new javax.swing.JTextField();
        btnLibroAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaLibros = new javax.swing.JTextArea();
        panelPrestamo = new javax.swing.JPanel();
        cbLibros = new javax.swing.JComboBox<>();
        txtDniPrestamo = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JTextField();
        btnAgregarPrestamo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaPrestamo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtUserNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre del usuario"));

        txtUserDni.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI del usuario"));

        btnUserAgregar.setText("Agregar");
        btnUserAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAgregarActionPerformed(evt);
            }
        });

        listaUsuarios.setColumns(20);
        listaUsuarios.setRows(5);
        jScrollPane1.setViewportView(listaUsuarios);

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(txtUserNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserDni, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUsuarioLayout.createSequentialGroup()
                        .addComponent(btnUserAgregar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtUserNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtUserDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUserAgregar)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gestión de usuarios", panelUsuario);

        txtLibroTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder("Titulo del libro"));

        txtLibroAutor.setBorder(javax.swing.BorderFactory.createTitledBorder("Autor"));

        txtLibroPaginas.setBorder(javax.swing.BorderFactory.createTitledBorder("Páginas"));

        txtLibroUnidades.setBorder(javax.swing.BorderFactory.createTitledBorder("Unidades"));

        btnLibroAgregar.setText("Agregar");
        btnLibroAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibroAgregarActionPerformed(evt);
            }
        });

        listaLibros.setColumns(20);
        listaLibros.setRows(5);
        jScrollPane2.setViewportView(listaLibros);

        javax.swing.GroupLayout panelLibroLayout = new javax.swing.GroupLayout(panelLibro);
        panelLibro.setLayout(panelLibroLayout);
        panelLibroLayout.setHorizontalGroup(
            panelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLibroLayout.createSequentialGroup()
                        .addComponent(btnLibroAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(txtLibroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLibroLayout.createSequentialGroup()
                        .addComponent(txtLibroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLibroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLibroUnidades)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelLibroLayout.setVerticalGroup(
            panelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtLibroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLibroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLibroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLibroUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLibroAgregar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestión de libros", panelLibro);

        cbLibros.setBorder(javax.swing.BorderFactory.createTitledBorder("Libro"));

        txtDniPrestamo.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI"));

        txtFechaInicio.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha inicio"));

        txtFechaFin.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de entrega"));

        btnAgregarPrestamo.setText("Agregar");
        btnAgregarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPrestamoActionPerformed(evt);
            }
        });

        listaPrestamo.setColumns(20);
        listaPrestamo.setRows(5);
        jScrollPane3.setViewportView(listaPrestamo);

        javax.swing.GroupLayout panelPrestamoLayout = new javax.swing.GroupLayout(panelPrestamo);
        panelPrestamo.setLayout(panelPrestamoLayout);
        panelPrestamoLayout.setHorizontalGroup(
            panelPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPrestamoLayout.createSequentialGroup()
                        .addGroup(panelPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFechaInicio)
                            .addComponent(cbLibros, 0, 147, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(panelPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDniPrestamo)
                            .addComponent(txtFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                    .addComponent(btnAgregarPrestamo)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelPrestamoLayout.setVerticalGroup(
            panelPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrestamoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDniPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarPrestamo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Préstamos", panelPrestamo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAgregarActionPerformed
        usuario.setNombre(txtUserNombre.getText());
        usuario.setDni(txtUserDni.getText());
        usuarios.add(usuario);
        listaUsuarios();
    }//GEN-LAST:event_btnUserAgregarActionPerformed

    private void btnLibroAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibroAgregarActionPerformed
        libro.setAutor(txtLibroAutor.getText());
        libro.setTitulo(txtLibroTitulo.getText());
        libro.setPaginas(Integer.valueOf(
                txtLibroPaginas.getText()));
        libro.setDisponibles(Integer.valueOf(
                txtLibroUnidades.getText()));
        libros.add(libro);
        listaLibros();
    }//GEN-LAST:event_btnLibroAgregarActionPerformed

    private void btnAgregarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPrestamoActionPerformed
        prestamo.setLibro((Libro) cbLibros.getSelectedItem());
        prestamo.setDni(txtDniPrestamo.getText());
        prestamo.setFechaInicio(
                LocalDate.now()
        );
        prestamo.setFechaEntrega(
                LocalDate.parse(
                        txtFechaFin.getText()
                )
        );
        prestamos.add(prestamo);
        listadoPrestamos();
    }//GEN-LAST:event_btnAgregarPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPrestamo;
    private javax.swing.JButton btnLibroAgregar;
    private javax.swing.JButton btnUserAgregar;
    private javax.swing.JComboBox<Libro> cbLibros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea listaLibros;
    private javax.swing.JTextArea listaPrestamo;
    private javax.swing.JTextArea listaUsuarios;
    private javax.swing.JPanel panelLibro;
    private javax.swing.JPanel panelPrestamo;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JTextField txtDniPrestamo;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtLibroAutor;
    private javax.swing.JTextField txtLibroPaginas;
    private javax.swing.JTextField txtLibroTitulo;
    private javax.swing.JTextField txtLibroUnidades;
    private javax.swing.JTextField txtUserDni;
    private javax.swing.JTextField txtUserNombre;
    // End of variables declaration//GEN-END:variables

    private void listaUsuarios() {
        usuario = new Usuario();
        txtUserDni.setText(null);
        txtUserNombre.setText(null);
        listaUsuarios.setText(null);
        //Cargar usuarios al TXTArea
        for (Usuario t : usuarios) {
            listaUsuarios.append(t.toString());
        }
    }

    private void listaLibros() {
        libro = new Libro();
        txtLibroAutor.setText(null);
        txtLibroTitulo.setText(null);
        txtLibroPaginas.setText(null);
        txtLibroUnidades.setText(null);
        listaLibros.setText(null);
        cbLibros.removeAllItems();
        //Cargar usuarios al TXTArea
        for (Libro t : libros) {
            listaLibros.append(t.toString());
            cbLibros.addItem(t);
        }
    }

    private void listadoPrestamos() {
        prestamo = new Prestamo();
        txtDniPrestamo.setText(null);
        txtFechaFin.setText(null);
        txtFechaInicio.setText(null);
        listaPrestamo.setText(null);
        //Cargar usuarios al TXTArea
        for (Prestamo t : prestamos) {
            listaPrestamo.append(t.toString());
        }
    }
}
